# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
null_vector.nbytes

80

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
array1 = np.arange(10,50)
print(array1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
array1_desc = array1[::-1]
print(array1_desc)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
array2 = np.arange(0,9).reshape(3,3)
print(array2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
array3 = np.array([1,2,0,0,4,0])
indices = np.nonzero(array3)
print(indices[0])

[0 1 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [13]:
identity = np.identity(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [14]:
array4 = np.random.random((3,3,3))
print(array4)

[[[0.28178584 0.49842461 0.61155012]
  [0.29813139 0.6580551  0.92158309]
  [0.09375194 0.33126011 0.60222936]]

 [[0.87907619 0.65285418 0.96224829]
  [0.25675466 0.50399027 0.2201329 ]
  [0.29469293 0.83187169 0.48686995]]

 [[0.04152901 0.90221292 0.47046576]
  [0.44279007 0.46214794 0.63678791]
  [0.90311382 0.94805005 0.4780163 ]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [16]:
array5 = np.random.random((10,10))
print(array5)
print('최솟값:', np.min(array5))
print('최댓값:', np.max(array5))

[[0.79275346 0.74921083 0.52569332 0.78864488 0.63782845 0.19082211
  0.57334728 0.91476912 0.86591928 0.78929205]
 [0.20066458 0.70424478 0.92807676 0.15619362 0.65313054 0.02386615
  0.51608515 0.02808446 0.06626272 0.53151856]
 [0.839085   0.94278347 0.62508415 0.35637681 0.03805226 0.21900051
  0.16809124 0.30888098 0.99221703 0.62364415]
 [0.39116831 0.32807063 0.23404115 0.8351784  0.31147376 0.73871152
  0.65431412 0.17345764 0.24710048 0.19770997]
 [0.9558764  0.72268479 0.4373199  0.23389229 0.79303957 0.08612341
  0.55683909 0.51486718 0.88375147 0.85790546]
 [0.10042396 0.58776922 0.81512041 0.0809718  0.8104664  0.17970986
  0.76553577 0.58455177 0.23270951 0.24770784]
 [0.64797869 0.70935138 0.45154224 0.04135497 0.67878991 0.91448624
  0.86826087 0.77290486 0.59919036 0.36138263]
 [0.41914041 0.24833894 0.84873561 0.28813608 0.52552105 0.61728826
  0.42944534 0.20889403 0.07477216 0.65267635]
 [0.2375071  0.27920965 0.46263917 0.10852276 0.90050966 0.32293566
  0.33594437

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [17]:
array6 = np.random.random(30)
print(array6)
print('평균값:', np.mean(array6))

[0.87144546 0.87244408 0.23359653 0.14472896 0.47947517 0.88410351
 0.18713627 0.36081015 0.24966544 0.59989406 0.40258772 0.6445256
 0.60902897 0.69654288 0.54537723 0.02320765 0.14384758 0.69083363
 0.03295324 0.83701243 0.69079427 0.12597188 0.42620988 0.22351342
 0.43083163 0.90874609 0.29667294 0.63115621 0.41899011 0.33474311]
평균값: 0.46656153593420135


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [18]:
array7 = np.ones((5,5))
array7[1:-1,1:-1] = 0
print(array7)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, True

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [25]:
array8 = np.zeros((5,5))
array8[np.arange(1,5), np.arange(4)] = np.arange(1,5)
print(array8)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
array9 = np.zeros((8,8))
array9[1::2, ::2] = 1
array9[::2, 1::2] = 1
print(array9)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [24]:
array10 = np.unravel_index(99, (6,7,8))
print(np.array(array10))

[1 5 3]


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [27]:
X = np.random.random((5,5))
Z = (X - np.mean(X))/np.std(X)
print(Z)

[[-1.31428955  1.49403679  1.3757223   1.30576149  0.12497887]
 [-0.9053022   0.4246312  -1.34511654  0.13000044 -0.56856558]
 [-0.5269295   0.69801589  1.7823198   0.00521398 -1.32616319]
 [-1.10441737 -1.16927827  0.02400848  0.93669325  1.71336684]
 [ 0.18886045 -0.49327571 -0.48856858  0.29274757 -1.25445085]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [29]:
color = np.dtype([
    ("R", np.ubyte),
    ("G", np.ubyte),
    ("B", np.ubyte),
    ("A", np.ubyte)
])
print(color)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]
