# 03.넘파이(Numerical Python)
- 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 하는 대표 패키지
- 루프를 사용하지 않음
- 빠른 연산 속도 보장
- C/C++과 같은 저수준 언어 기반의 호환 API를 제공

넘파이는 매우 빠른 배열 연산을 보장하지만, 파이썬 언어가 가지는 수행 성능의 제약때문에 성능이 중요한 부분은 C/C++ 기반 코드로 작성하고 이를 넘파이에서 호출하는 방식으로 쉽게 통합이 가능함.

넘파이는 편의성과 다양한 API 지원 측면에서 아쉬운 부분이 많음. 그러나 많은 머신러닝 알고리즘이 넘파이 기반으로 작성되어있고 알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용하기 때문에 넘파이를 이해하는 것은 파이썬에서 매우 중요함.

### 넘파이 ndarray 개요

In [ ]:
import numpy as np #약어로모듈표현

- ndarray: 넘파이의 기반 데이터 타입
- 다차원 배열과 다양한 연산 수행

`array()` ndarra로 변환  
생성된 ndarray 배열의 shape 변수를 통해 ndarray배열의 차원을 알 수 있음


In [ ]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


`np.array()`: ndarray로 변환을 원하는 객체를 인자로 입력하면 ndarray를 반환함   
`ndarray.shape`: ndarray의 차원과 크기를 tuple형태로 나타냄
- array1 (3,): 1차원 array 3개의 데이터를 가짐
- array2 (2,3): 2차원 array 행2열3
- array3 (1,3): 2차원 array 행1열3

In [ ]:
print('array1: {0}차원, array2: {1}차원, array3:{2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:2차원


- 리스트[] 1차원
- 리스트 [[]] 2차원

###ndaray의 데이터 타입
ndarray의 데이터는 숫자, 문자열, 불 등 모두 가능  
ex) 숫자형: int, unsigned int, float, complex

ndarray 내의 데이터 타입은 같은 데이터 타입만 가능   
즉, int와 float는 함께 있을 수 없음

In [ ]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


만약 다른 데이터 유형이 섞인 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄적으로 적용

In [ ]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


array2 숫자형 값 1, 2 -> 문자열 값 '1', '2'  
array3 int 1, 2 -> float64

`astype()`: 인자로 원하는 타입을 문자열로 지정하면 ndarray 내 데이터값의 타입 변경이 가능함

In [ ]:
#int32 -> float64 다시 float64 -> int32
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


###ndarray를 편리하게 생성하기 - arange, zeros, ones
`arange()` array를 `range()`로 표현  
0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터 값으로 변환함  
default 함수 인자는 stop 값이며 0부터 stop값인 10에 -1을 한 0까지의 연속 숫자로 구성된 1차원 ndarray를 만듦  
range와 유사하게 start값도 부여해 0이 아닌 다른 값부터 시작한 연속 값을 부여할 수도 있음

In [ ]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


`zero()` 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndaray로 반환  
`ones()` 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray로 반환  
함수 인자로 dtype을 지정하지 않으면 default로 float64형의 데이터로 ndarray를 채움

In [ ]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


###ndarray의 차원과 크기를 변경하는 reshape()
`rehape()`: ndarray를 특정 차원 및 크기로 변환  
지정된 사이즈로 변경이 불가능하면 오류 발생

In [ ]:
array1 = np.arange(10)
print('array1：\n', array1)

array2 = array1.reshape(2, 5)
print('array2：\n', array2)

array3 = array1.reshape(5, 2)
print('array3：\n', array3)

array1：
 [0 1 2 3 4 5 6 7 8 9]
array2：
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3：
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
array1.reshape(4, 3)

ValueError: cannot reshape array of size 10 into shape (4,3)

`reshape()`: 인자로 -1을 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환  
array1 0~9 데이터  
array2 행-1열5: array1과 호환되는 2차원 ndarray로 변환하되 고정된 5개의 칼럼에 맞는 행을 자동 생성해 변환  
array3 행5열-1: array1과 호환되는 2차원 ndarray로 변환하되 고정된 5개의 로우에 맞는 열을 자동 생성해 변환  

In [ ]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


-1을 사용하더라도 호환될 수 없는 형태는 변환 불가

In [ ]:
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

`reshape(-1,1)` 원본 ndarray가 어떤 형태라도 2차원이고, 여러개의 로우를 가지되 반드시 1개의 탈럼을 가진 ndarray로 변환됨을 보장  
`tolist()` ndarray 리스트를 자료형으로 변환

In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d：\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5：\n', array5.tolist())
print('array5 shape：', array5.shape)

# 1 차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6：\n', array6.tolist())
print('array6 shape：', array6.shape)

array3d：
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5：
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape： (8, 1)
array6：
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape： (8, 1)


###넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)
1. 특정한 데이터만 추출: 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환
2. 슬라이싱(Slicing): 연속된 인덱스상의 ndarray를 추출하는 방식   
‘：’ 기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스-1 위치에 있는 데이터의 ndarray 반환함  
ex) 1：5 시작 인덱스 1과 종료 인덱스 4까지에 해당하는 ndarray 반환
3. 팬시 인덱싱(Fancy Indexing)： 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray 반환
4. 불린 인덱싱(Boolean Indexing)： 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray 반환

**단일 값 추출**  
ndarray 객체에 해당하는 위치의 인덱스 값을 []안에 입력해 1개의 데이터 값을 선택함  
index는 0부터 시작 array1[2]는 3번째 위치한 데이터값 의미  
array1[2]는 ndarray타입이 아니라 ndarray내의 데이터 값임

In [ ]:
#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [ ]:
print('맨 뒤의 값:', array1[-1],'맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [ ]:
#단일 인덱스를 이용해 ndarray 내의 데이터 값 수정
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


2차원은 1차원과 달리 콤마로 분리된 열과 행의 위치의 인덱스를 통해 데이터에 접근함  

In [ ]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


**슬라이싱**  
':'이용해 연속한 데이터를 슬라이싱해서 추출함
':' 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작인덱스~종료인덱스-1 데이터의 ndarray를 반환

In [ ]:
array1 - np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[9 2 3]
<class 'numpy.ndarray'>


1. ‘：’시작 인덱스를 생략시 자동으로 맨 처음 인덱스인 0으로 간주
2. ‘:’ 종료 인덱스를 생략시 자동으로 맨 마지막 인덱스로 간주
3. ‘：’시작/종료 인덱스를 생략시 자동으로  처음/마지막 인덱스로 간주

In [ ]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[：, :] \n', array2d[:, :])
print('array2d[：2, 1:] \n', array2d[:2, 1:])
print('array2d[：2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[：, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[：2, 1:] 
 [[2 3]
 [5 6]]
array2d[：2, 0] 
 [1 4]


2차원 ndarray 뒤에 오는 인덱스를 없애면 1차원을 반환

In [ ]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape,'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


**팬시 인덱싱(Fancy Indexing)**  
리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식


In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0, 1], 2]
print('array2d[[0,1],2]=>', array3.tolist())

array4 = array2d[[0, 1], 0:2]
print('array2d[[0,1],0:2]=>', array4.tolist())

array5 = array2d[[0, 1]]
print('array2d[[0,1]]=>', array5.tolist())

array2d[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


**불린 인덱싱(Boolean indexing)**  
조건 필터링과 검색을 동시에 할 수 있어 자주 사용되는 인덱싱 방식

In [ ]:
array1d = np.arange(start=1, stop=10)
#[]안에 array1d>5 Boolean indexing을 적용
array3 = array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:', array3)

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


In [ ]:
array1d >5
#ndarray에 조건식을 붙이면 False/True로 이뤄진 ndarray객체가 반환됨

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
#위와 동일한 불린 ndarray를 만들고 array1d[] 내에 인덱스를 입력하면 동일한 데이터 세트가 반환됨
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 ：', array3)

불린 인덱스로 필터링 결과 ： [6 7 8 9]


불린 인덱싱이 동작하는 단계
- Step 1： ndarray의 필터링 조건을 [ ] 안에 기재  
- Step 2： False 값 무시하고 True 값 인덱스만 저장  
(True값 자체인 1을 저장하는 것이 아니라 True값을 가진 인덱스를 저장）  
- Step 3： 저장된 인덱스 데이터 세트로 ndarray 조회

###행렬의 정렬 一 sort()와 argsort()
**행렬정렬**
- `np.sort()`: 넘파이에서 `sort()`를 호출하는 방식  
원 행렬을 그대로 유지한 채 원 행렬의 정렬된 행렬을 바환
- `ndarray.sort()`: 행렬 자체에서 `sort()`를 호출하는 방식  
원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None

In [ ]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [ ]:
#[::-1] 내림차순으로 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


행렬이 2차원 이상이면 axis 축 값을 설정해 로우 또는 칼럼 방향으로 정렬 수행 가능

In [ ]:
array2d = np.array([[8, 12],
                    [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


**정렬된 행렬의 인덱스를 반환하기**  
`np.argsort()`: 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환

In [ ]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [ ]:
#내림차순
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [ ]:
name_array = np.array(['John1', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John1' 'Sarah' 'Samuel' 'Mike' 'Kate']


###선형대수 연산 - 행렬 내적과 전치 행렬 구하기
**행렬 내적(행렬 곱)**  
두 행렬의 내적은 `np.dot()`을 이용해 계산

In [ ]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


**전치 행렬**  
원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬  
`transpose()`를 이용

In [ ]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
